// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/callback.ts";
import * as $2 from "./routes/api/login.ts";
import * as $3 from "./routes/api/logout.ts";
import * as $4 from "./routes/api/message.ts";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/Chat.tsx";
import * as $$1 from "./islands/Chatbox.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/callback.ts": $1,
    "./routes/api/login.ts": $2,
    "./routes/api/logout.ts": $3,
    "./routes/api/message.ts": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/Chat.tsx": $$0,
    "./islands/Chatbox.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
